In [42]:
import pandas as pd


link="https://github.com/PoliticayGobiernoPUCP/Gob_TomaDeDecisiones/raw/refs/heads/master/dataCrim.xlsx"
crim=pd.read_excel(link,dtype={'cod': str})
crim.head()

,cod,distrito,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,010101,CHACHAPOYAS,503.0,702.0,1177.0,1087.0,801.0,628.0,674.0,728.0,917.0,857.0
1,010102,ASUNCION,4.0,6.0,1.0,2.0,1.0,2.0,3.0,NaN,NaN,5.0
2,010103,BALSAS,NaN,NaN,11.0,8.0,14.0,21.0,27.0,17.0,16.0,13.0
3,010104,CHETO,2.0,2.0,NaN,1.0,1.0,3.0,5.0,3.0,1.0,1.0
4,010105,CHILIQUIN,2.0,4.0,2.0,2.0,NaN,3.0,3.0,NaN,1.0,2.0

In [43]:
crim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1860 entries, 0 to 1859
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cod       1860 non-null   object
 1   distrito  1860 non-null   object
 2   2015      1509 non-null   float64
 3   2016      1516 non-null   float64
 4   2017      1633 non-null   float64
 5   2018      1600 non-null   float64
 6   2019      1505 non-null   float64
 7   2020      1590 non-null   float64
 8   2021      1667 non-null   float64
 9   2022      1668 non-null   float64
 10  2023      1671 non-null   float64
 11  2024      1617 non-null   float64
dtypes: float64(10), object(2)
memory usage: 174.5+ KB

In [52]:
crim[crim.distrito.str.contains('MIRAF')]

,cod,distrito,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,distrito_en
341,040110,MIRAFLORES,551.0,617.0,1548.0,1542.0,1430.0,950.0,1100.0,1160.0,1642.0,1389.0,MIRAFLORES
942,100506,MIRAFLORES,1.0,NaN,4.0,NaN,1.0,8.0,3.0,6.0,5.0,NaN,MIRAFLORES
1296,150122,MIRAFLORES,2626.0,1480.0,2485.0,2782.0,2755.0,1657.0,2838.0,4424.0,8219.0,7431.0,MIRAFLORES
1307,150133,SAN JUAN DE MIRAFLORES,5154.0,5696.0,5230.0,6617.0,4991.0,3014.0,4887.0,5650.0,5825.0,5201.0,SAN JUAN DE MIRAFLORES
1427,151021,MIRAFLORES,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,MIRAFLORES

In [44]:
import geopandas as gpd

dis=gpd.read_file('DISTRITOS1874.shp')
dis.head()

,DEPARTAMEN,PROVINCIA,DISTRITO,INSTITUCIO,geometry
0,TACNA,TACNA,CORONEL GREGORIO ALBARRACIN LANCHIPA,IGN,"POLYGON ((-70.17413 -18.12896, -70.17461 -18.1..."
1,TACNA,TACNA,POCOLLAY,IGN,"POLYGON ((-69.93475 -17.92557, -69.90467 -17.9..."
2,TACNA,TACNA,CALANA,IGN,"POLYGON ((-70.11604 -17.91106, -70.11457 -17.9..."
3,TACNA,TACNA,TACNA,IGN,"POLYGON ((-70.31490 -17.94498, -70.30682 -17.9..."
4,TACNA,TACNA,SAMA,IGN,"POLYGON ((-70.42497 -17.88934, -70.48022 -17.9..."

In [45]:
from unidecode import unidecode


# Convert characters to their closest ASCII equivalents
dis['distrito_en']=dis.DISTRITO.apply(unidecode).str.upper().str.strip()
crim['distrito_en']=crim.distrito.apply(unidecode).str.upper().str.strip()

In [46]:
onlyCrim=set(crim.distrito_en) - set(dis.distrito_en)
onlyCrim

{'ALLAUCA',
 'ANCO_HUALLO',
 'CARAYBAMBA',
 'ESTIQUE-PAMPA',
 'HUANCA-HUANCA',
 'HUAYLLAY GRANDE',
 'MASMA CHICCHE',
 'NASCA',
 'PAPAPLAYA',
 'QUISQUI (KICHKI)',
 'RINCONADA LLICUAR',
 'SAN JOSE DE LOS MOLINOS',
 'SAN JOSE DE TICLLAS',
 'SAN JUAN DE ISCOS',
 'SANTA CRUZ DE TOLEDO',
 'TRES UNIDOS',
 'TUNAN MARCA'}

In [47]:
onlyDis=set(dis.distrito_en)-set(crim.distrito_en)
onlyDis

{'ANCO HUALLO',
 'AYAUCA',
 'CANIS',
 'CARAIBAMBA',
 'COPA',
 'ESTIQUE PAMPA',
 'HUACLLAN',
 'HUALLAY GRANDE',
 'HUAMPARA',
 'HUANCA HUANCA',
 'LAMPIAN',
 'LOS CHANKAS',
 'MAGDALENA VIEJA',
 'MASMA-CHICCHE',
 'NAZCA',
 'ORONCCOY',
 'PAPA-PLAYA',
 'QUISQUI',
 'RINCONADA-LLICUAR',
 'ROSA PANDURO',
 'SAN JOSE  DE TICLLAS',
 'SAN JOSE DE  LOS MOLINOS',
 'SAN JUAN DE YSCOS',
 'SAN PEDRO DE HUANCAYRE',
 'SANTA CRUZ DE TOLED',
 'SANTIAGO DE TUCUMA',
 'SUMBILCA',
 'TRES-UNIDOS',
 'TUNAN-MARCA',
 'VEINTISIETE DE NOVIEMBRE',
 'YAGUAS',
 'YAQUERANA'}

In [35]:
from thefuzz.process import extractOne as getBest
[(c,getBest(c,onlyDis)) for c in onlyCrim]

[('PAPAPLAYA', ('PAPA-PLAYA', 95)),
 ('ALLAUCA', ('AYAUCA', 77)),
 ('SAN JOSE DE LOS MOLINOS', ('SAN JOSE DE  LOS MOLINOS', 98)),
 ('SAN JOSE DE TICLLAS', ('SAN JOSE  DE TICLLAS', 97)),
 ('NASCA', ('NAZCA', 80)),
 ('QUISQUI (KICHKI)', ('QUISQUI', 90)),
 ('RINCONADA LLICUAR', ('RINCONADA-LLICUAR', 100)),
 ('SANTA CRUZ DE TOLEDO', ('SANTA CRUZ DE TOLED', 97)),
 ('HUAYLLAY GRANDE', ('HUALLAY GRANDE', 97)),
 ('HUANCA-HUANCA', ('HUANCA HUANCA', 100)),
 ('SAN JUAN DE ISCOS', ('SAN JUAN DE YSCOS', 94)),
 ('MASMA CHICCHE', ('MASMA-CHICCHE', 100)),
 ('CARAYBAMBA', ('CARAIBAMBA', 90)),
 ('TRES UNIDOS', ('TRES-UNIDOS', 100)),
 ('ANCO_HUALLO', ('ANCO HUALLO', 91)),
 ('TUNAN MARCA', ('TUNAN-MARCA', 100)),
 ('ESTIQUE-PAMPA', ('ESTIQUE PAMPA', 100))]

In [37]:
changesCrim={c:getBest(c,onlyDis)[0] for c in onlyCrim}
changesCrim

{'PAPAPLAYA': 'PAPA-PLAYA',
 'ALLAUCA': 'AYAUCA',
 'SAN JOSE DE LOS MOLINOS': 'SAN JOSE DE  LOS MOLINOS',
 'SAN JOSE DE TICLLAS': 'SAN JOSE  DE TICLLAS',
 'NASCA': 'NAZCA',
 'QUISQUI (KICHKI)': 'QUISQUI',
 'RINCONADA LLICUAR': 'RINCONADA-LLICUAR',
 'SANTA CRUZ DE TOLEDO': 'SANTA CRUZ DE TOLED',
 'HUAYLLAY GRANDE': 'HUALLAY GRANDE',
 'HUANCA-HUANCA': 'HUANCA HUANCA',
 'SAN JUAN DE ISCOS': 'SAN JUAN DE YSCOS',
 'MASMA CHICCHE': 'MASMA-CHICCHE',
 'CARAYBAMBA': 'CARAIBAMBA',
 'TRES UNIDOS': 'TRES-UNIDOS',
 'ANCO_HUALLO': 'ANCO HUALLO',
 'TUNAN MARCA': 'TUNAN-MARCA',
 'ESTIQUE-PAMPA': 'ESTIQUE PAMPA'}

In [39]:
crim.replace({'distrito_en':changesCrim},inplace=True)

In [40]:
onlyCrim=set(crim.distrito_en) - set(dis.distrito_en)
onlyCrim

set()

In [41]:
onlyDis=set(dis.distrito_en)-set(crim.distrito_en)
onlyDis

{'CANIS',
 'COPA',
 'HUACLLAN',
 'HUAMPARA',
 'LAMPIAN',
 'LOS CHANKAS',
 'MAGDALENA VIEJA',
 'ORONCCOY',
 'ROSA PANDURO',
 'SAN PEDRO DE HUANCAYRE',
 'SANTIAGO DE TUCUMA',
 'SUMBILCA',
 'VEINTISIETE DE NOVIEMBRE',
 'YAGUAS',
 'YAQUERANA'}